import { Member } from './member';

export const MEMBERS: any[] = [
  {
    "id": "1",
    "password": "password",
    "firstname": "Woogi",
    "lastname": "Min",
    //"admin": false,
    "subject": "가정의학과",
    "type": "University",
    "country": "South Korea",
    "city": "Seoul",
    "address": "서초구 강남대로 311 한화빌딩 14층",
    "organization": "경북대학교",
    "postCode": "123456",
    "managerName": "Sogi Choi",
    "phoneNum": "1234567890",
    "mobileNum": "1234567890"
  },
  {
    "id": "2",
    "password": "abcdef",
    "firstname": "Sogi",
    "lastname": "Choi",
    //"admin": false,
    "subject": "내과",
    "type": "Normal hospital",
    "country": "South Korea",
    "city": "Daegu",
    "address": "서초구 강남대로 311 한화빌딩 14층",
    "organization": "세브란스병원",
    "postCode": "123456",
    "managerName": "Sogi Choi",
    "phoneNum": "1234567890",
    "mobileNum": "1234567890"
  },
  {
    "id": "3",
    "password": "abcdef",
    "firstname": "Hyunyong",
    "lastname": "Cho",
    //"admin": false,
    "subject": "마취통증의학과",
    "type": "University",
    "country": "South Korea",
    "city": "Seoul",
    "address": "서초구 강남대로 311 한화빌딩 14층",
    "organization": "경북대학교",
    "postCode": "123456",
    "managerName": "Sogi Choi",
    "phoneNum": "1234567890",
    "mobileNum": "1234567890"
  },
  {
    "id": "4",
    "password": "abcdef",
    "firstname": "Kyungseok",
    "lastname": "Roe",
    //"admin": false,
    "subject": "정형외과",
    "type": "University",
    "country": "South Korea",
    "city": "Seoul",
    "address": "서초구 강남대로 311 한화빌딩 14층",
    "organization": "경북대학교",
    "postCode": "123456",
    "managerName": "Sogi Choi",
    "phoneNum": "1234567890",
    "mobileNum": "1234567890"
  },
  {
    "id": "5",
    "password": "abcdef",
    "firstname": "Haewon",
    "lastname": "Choi",
    //"admin": false,
    "subject": "재활의학과",
    "type": "Normal hospital",
    "country": "Japan",
    "city": "Tokyo",
    "address": "서초구 강남대로 311 한화빌딩 14층",
    "organization": "Tokyo University",
    "postCode": "123456",
    "managerName": "Sogi Choi",
    "phoneNum": "1234567890",
    "mobileNum": "1234567890"
  },
  {
    "id": "6",
    "password": "abcdef",
    "firstname": "Jihye",
    "lastname": "Song",
    //"admin": false,
    "subject": "재활의학과",
    "type": "University",
    "country": "South Korea",
    "city": "Daegu",
    "address": "서초구 강남대로 311 한화빌딩 14층",
    "organization": "서울대학교",
    "postCode": "123456",
    "managerName": "Sogi Choi",
    "phoneNum": "1234567890",
    "mobileNum": "1234567890"
  },
  {
    "id": "7",
    "password": "abcdef",
    "firstname": "Soojin",
    "lastname": "Park",
    //"admin": false,
    "subject": "재활의학과",
    "type": "Normal hospital",
    "country": "United Stated",
    "city": "Newyork",
    "address": "서초구 강남대로 311 한화빌딩 14층",
    "organization": "경북대학교",
    "postCode": "123456",
    "managerName": "Sogi Choi",
    "phoneNum": "1234567890",
    "mobileNum": "1234567890"
  },
  {
    "id": "8",
    "password": "abcdef",
    "firstname": "Baekjin",
    "lastname": "Lee",
    //"admin": false,
    "subject": "재활의학과",
    "type": "Korean medicine",
    "country": "South Korea",
    "city": "Seoul",
    "address": "서초구 강남대로 311 한화빌딩 14층",
    "organization": "서울대학교",
    "postCode": "123456",
    "managerName": "Sogi Choi",
    "phoneNum": "1234567890",
    "mobileNum": "1234567890"
  },
  {
    "id": "9",
    "password": "abcdef",
    "firstname": "Soyul",
    "lastname": "Lee",
    //"admin": false,
    "subject": "재활의학과",
    "type": "Normal hospital",
    "country": "United Stated",
    "city": "Newyork",
    "address": "서초구 강남대로 311 한화빌딩 14층",
    "organization": "서울대학교",
    "postCode": "123456",
    "managerName": "Sogi Choi",
    "phoneNum": "1234567890",
    "mobileNum": "1234567890"
  },
  {
    "id": "10",
    "password": "abcdef",
    "firstname": "David",
    "lastname": "Choi",
    //"admin": false,
    "subject": "재활의학과",
    "type": "University",
    "country": "South Korea",
    "city": "Daegu",
    "address": "서초구 강남대로 311 한화빌딩 14층",
    "organization": "경북대학교",
    "postCode": "123456",
    "managerName": "Sogi Choi",
    "phoneNum": "1234567890",
    "mobileNum": "1234567890"
  },
  {
    "id": "11",
    "password": "abcdef",
    "firstname": "Stephanie",
    "lastname": "Lee",
    //"admin": false,
    "subject": "재활의학과",
    "type": "University",
    "country": "United Stated",
    "city": "San Francisco",
    "address": "서초구 강남대로 311 한화빌딩 14층",
    "organization": "세브란스병원",
    "postCode": "123456",
    "managerName": "Sogi Choi",
    "phoneNum": "1234567890",
    "mobileNum": "1234567890",
  },
  {
    "id": "12",
    "password": "abcdef",
    "firstname": "Yul",
    "lastname": "Song",
    //"admin": false,
    "subject": "재활의학과",
    "type": "Normal hospital",
    "country": "South Korea",
    "city": "Daegu",
    "address": "서초구 강남대로 311 한화빌딩 14층",
    "organization": "성모병원",
    "postCode": "123456",
    "managerName": "Sogi Choi",
    "phoneNum": "1234567890",
    "mobileNum": "1234567890"
  },
  {
    "id": "13",
    "password": "abcdef",
    "firstname": "Hyori",
    "lastname": "Lee",
    //"admin": false,
    "subject": "마취통증의학과",
    "type": "Korean medicine",
    "country": "South Korea",
    "city": "Seoul",
    "address": "서초구 강남대로 311 한화빌딩 14층",
    "organization": "경북대학교",
    "postCode": "123456",
    "managerName": "Sogi Choi",
    "phoneNum": "1234567890",
    "mobileNum": "1234567890"
  },
  {
    "id": "14",
    "password": "abcdef",
    "firstname": "Jaewoo",
    "lastname": "Kim",
    //"admin": false,
    "subject": "마취통증의학과",
    "type": "University",
    "country": "South Korea",
    "city": "Seoul",
    "address": "서초구 강남대로 311 한화빌딩 14층",
    "organization": "성모병원",
    "postCode": "123456",
    "managerName": "Sogi Choi",
    "phoneNum": "1234567890",
    "mobileNum": "1234567890"
  },
  {
    "id": "15",
    "password": "abcdef",
    "firstname": "Christ",
    "lastname": "Little",
    //"admin": false,
    "subject": "마취통증의학과",
    "type": "General",
    "country": "Japan",
    "city": "Tokyo",
    "address": "서초구 강남대로 311 한화빌딩 14층",
    "organization": "Tokyo University",
    "postCode": "123456",
    "managerName": "Sogi Choi",
    "phoneNum": "1234567890",
    "mobileNum": "1234567890"
  },
  {
    "id": "16",
    "password": "abcdef",
    "firstname": "Min",
    "lastname": "Park",
    //"admin": false,
    "subject": "가정의학과",
    "type": "Normal hospital",
    "country": "South Korea",
    "city": "Seoul",
    "address": "서초구 강남대로 311 한화빌딩 14층",
    "organization": "경북대학교",
    "postCode": "123456",
    "managerName": "Sogi Choi",
    "phoneNum": "1234567890",
    "mobileNum": "1234567890"
  },
  {
    "id": "17",
    "password": "abcdef",
    "firstname": "Youngjin",
    "lastname": "Yun",
    //"admin": false,
    "subject": "마취통증의학과",
    "type": "Clinic",
    "country": "South Korea",
    "city": "Seoul",
    "address": "서초구 강남대로 311 한화빌딩 14층",
    "organization": "서울대학교",
    "postCode": "123456",
    "managerName": "Sogi Choi",
    "phoneNum": "1234567890",
    "mobileNum": "1234567890"
  },
  {
    "id": "18",
    "password": "abcdef",
    "firstname": "Siri",
    "lastname": "Hyun",
    //"admin": false,
    "subject": "가정의학과",
    "type": "General",
    "country": "South Korea",
    "city": "Daegu",
    "address": "서초구 강남대로 311 한화빌딩 14층",
    "organization": "경북대학교",
    "postCode": "123456",
    "managerName": "Sogi Choi",
    "phoneNum": "1234567890",
    "mobileNum": "1234567890"
  },
  {
    "id": "19",
    "password": "abcdef",
    "firstname": "Hanna",
    "lastname": "Sap",
    //"admin": false,
    "subject": "정형외과",
    "type": "University",
    "country": "South Korea",
    "city": "Seoul",
    "address": "서초구 강남대로 311 한화빌딩 14층",
    "organization": "SAP",
    "postCode": "123456",
    "managerName": "Sogi Choi",
    "phoneNum": "1234567890",
    "mobileNum": "1234567890"
  }
];

// Test Data